version: '3.8'

services:
  api:
    build: ./
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    depends_on:
      - redis

  redis:
    image: "redis:alpine"

    command: redis-server

    ports:
     - 6378:6379

    environment:
     - REDIS_REPLICATION_MODE=master